import Head from "next/head";
import { Inter } from "@next/font/google";
import { useEffect, useState } from "react";
import LoginModal from "@/components/home/LoginModal";
import RegisterModal from "@/components/home/RegisterModal";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/footer/Footer";
export default function Home() {
  const [login, setLogin] = useState(false);
  const [register, setRegister] = useState(false);

  const handleLoginBtn = () => {
    setLogin(!login);
    console.log(login);
  };
  const closeLogin = () => {
    setLogin(false);
  };
  const closeRegister = () => {
    setRegister(false);
  };
  const handleRegisterBtn = () => {
    setRegister(!register);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={" text-black flex flex-col h-screen justify-between"}>
        <div className="justify-center">
          <div className="box-border   p-4 border-b-2 text-center mb-3">
            <div>
              <h1 className={"text-4xl"}>
                Pozdravljeni na Web Invoicer Aplikaciji
              </h1>
            </div>
            <div>
              <p className={"text-2xl"}>
                Za začetek izberite eno od možnosti v meniju
              </p>
            </div>
          </div>

          <div className="flex space-x-5 justify-center">
            <div>
              {!login && !register && (
                <button
                  onClick={handleLoginBtn}
                  className={
                    "bg-blue-500   hover:transition-all hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                  }
                >
                  Prijava
                </button>
              )}
            </div>

            <div>
              {!register && !login && (
                <button
                  onClick={handleRegisterBtn}
                  className={
                    "bg-blue-500 hover:bg-blue-700 hover:transition-all text-white font-bold py-2 px-4 rounded"
                  }
                >
                  Registracija
                </button>
              )}
            </div>
          </div>
          <div className="box-sized  flex justify-center pt-10">
            {login && <LoginModal cb={closeLogin} />}
            {register && <RegisterModal cb={closeRegister} />}
          </div>
        </div>
        <ToastContainer />
        <div>
          <div className="">
            <Footer />
          </div>
        </div>
      </main>
    </>
  );
}
